<?php


/**
 * This class adds structure of 't04_rolmenu' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug 20 18:05:54 2013
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class T04RolmenuMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.T04RolmenuMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(T04RolmenuPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(T04RolmenuPeer::TABLE_NAME);
		$tMap->setPhpName('T04Rolmenu');
		$tMap->setClassname('T04Rolmenu');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('t04_rolmenu_co_rolmenu_seq');

		$tMap->addPrimaryKey('CO_ROLMENU', 'CoRolmenu', 'INTEGER', true, null);

		$tMap->addForeignKey('CO_MENU', 'CoMenu', 'INTEGER', 't03_menu', 'CO_MENU', true, null);

		$tMap->addForeignKey('CO_ROL', 'CoRol', 'INTEGER', 't02_rol', 'CO_ROL', true, null);

		$tMap->addColumn('IN_VER', 'InVer', 'BOOLEAN', true, null);

	} // doBuild()

} // T04RolmenuMapBuilder
