<?php


/**
 * This class adds structure of 't05_documento' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug 20 18:05:54 2013
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class T05DocumentoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.T05DocumentoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(T05DocumentoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(T05DocumentoPeer::TABLE_NAME);
		$tMap->setPhpName('T05Documento');
		$tMap->setClassname('T05Documento');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('t05_documento_co_documento_seq');

		$tMap->addPrimaryKey('CO_DOCUMENTO', 'CoDocumento', 'INTEGER', true, null);

		$tMap->addColumn('TX_DOCUMENTO', 'TxDocumento', 'VARCHAR', true, 255);

		$tMap->addColumn('TX_TIPO', 'TxTipo', 'VARCHAR', true, 255);

	} // doBuild()

} // T05DocumentoMapBuilder
