<?php


/**
 * This class adds structure of 't07_producto' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug 20 18:05:54 2013
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class T07ProductoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.T07ProductoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(T07ProductoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(T07ProductoPeer::TABLE_NAME);
		$tMap->setPhpName('T07Producto');
		$tMap->setClassname('T07Producto');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('t07_producto_co_producto_seq');

		$tMap->addPrimaryKey('CO_PRODUCTO', 'CoProducto', 'BIGINT', true, null);

		$tMap->addColumn('TX_PRODUCTO', 'TxProducto', 'VARCHAR', true, 255);

		$tMap->addForeignKey('CO_PROVEEDOR', 'CoProveedor', 'INTEGER', 't06_proveedor', 'CO_PROVEEDOR', true, null);

		$tMap->addColumn('NU_PRECIO', 'NuPrecio', 'NUMERIC', true, 10);

		$tMap->addColumn('NU_PROCENTAJE_IVA', 'NuProcentajeIva', 'NUMERIC', true, 3);

		$tMap->addColumn('NU_PRECIO_IVA', 'NuPrecioIva', 'NUMERIC', true, 10);

		$tMap->addColumn('IN_ACTIVO', 'InActivo', 'BOOLEAN', false, null);

		$tMap->addColumn('NU_STOCK', 'NuStock', 'NUMERIC', false, null);

		$tMap->addColumn('IN_EXCENTO_IVA', 'InExcentoIva', 'BOOLEAN', false, null);

	} // doBuild()

} // T07ProductoMapBuilder
