<?php

/**
 * Base class that represents a row from the 't09_pedido_detalle' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug 20 18:05:54 2013
 *
 * @package    lib.model.om
 */
abstract class BaseT09PedidoDetalle extends BaseObject  implements Persistent {


  const PEER = 'T09PedidoDetallePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        T09PedidoDetallePeer
	 */
	protected static $peer;

	/**
	 * The value for the co_pedido_detalle field.
	 * @var        string
	 */
	protected $co_pedido_detalle;

	/**
	 * The value for the co_pedido field.
	 * @var        int
	 */
	protected $co_pedido;

	/**
	 * The value for the co_producto field.
	 * @var        int
	 */
	protected $co_producto;

	/**
	 * The value for the cn_producto field.
	 * @var        string
	 */
	protected $cn_producto;

	/**
	 * The value for the mo_viejo field.
	 * @var        string
	 */
	protected $mo_viejo;

	/**
	 * The value for the mo_nuevo field.
	 * @var        string
	 */
	protected $mo_nuevo;

	/**
	 * @var        T08Pedido
	 */
	protected $aT08Pedido;

	/**
	 * @var        T07Producto
	 */
	protected $aT07Producto;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseT09PedidoDetalle object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_pedido_detalle] column value.
	 * 
	 * @return     string
	 */
	public function getCoPedidoDetalle()
	{
		return $this->co_pedido_detalle;
	}

	/**
	 * Get the [co_pedido] column value.
	 * 
	 * @return     int
	 */
	public function getCoPedido()
	{
		return $this->co_pedido;
	}

	/**
	 * Get the [co_producto] column value.
	 * 
	 * @return     int
	 */
	public function getCoProducto()
	{
		return $this->co_producto;
	}

	/**
	 * Get the [cn_producto] column value.
	 * 
	 * @return     string
	 */
	public function getCnProducto()
	{
		return $this->cn_producto;
	}

	/**
	 * Get the [mo_viejo] column value.
	 * 
	 * @return     string
	 */
	public function getMoViejo()
	{
		return $this->mo_viejo;
	}

	/**
	 * Get the [mo_nuevo] column value.
	 * 
	 * @return     string
	 */
	public function getMoNuevo()
	{
		return $this->mo_nuevo;
	}

	/**
	 * Set the value of [co_pedido_detalle] column.
	 * 
	 * @param      string $v new value
	 * @return     T09PedidoDetalle The current object (for fluent API support)
	 */
	public function setCoPedidoDetalle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_pedido_detalle !== $v) {
			$this->co_pedido_detalle = $v;
			$this->modifiedColumns[] = T09PedidoDetallePeer::CO_PEDIDO_DETALLE;
		}

		return $this;
	} // setCoPedidoDetalle()

	/**
	 * Set the value of [co_pedido] column.
	 * 
	 * @param      int $v new value
	 * @return     T09PedidoDetalle The current object (for fluent API support)
	 */
	public function setCoPedido($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->co_pedido !== $v) {
			$this->co_pedido = $v;
			$this->modifiedColumns[] = T09PedidoDetallePeer::CO_PEDIDO;
		}

		if ($this->aT08Pedido !== null && $this->aT08Pedido->getCoPedido() !== $v) {
			$this->aT08Pedido = null;
		}

		return $this;
	} // setCoPedido()

	/**
	 * Set the value of [co_producto] column.
	 * 
	 * @param      int $v new value
	 * @return     T09PedidoDetalle The current object (for fluent API support)
	 */
	public function setCoProducto($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->co_producto !== $v) {
			$this->co_producto = $v;
			$this->modifiedColumns[] = T09PedidoDetallePeer::CO_PRODUCTO;
		}

		if ($this->aT07Producto !== null && $this->aT07Producto->getCoProducto() !== $v) {
			$this->aT07Producto = null;
		}

		return $this;
	} // setCoProducto()

	/**
	 * Set the value of [cn_producto] column.
	 * 
	 * @param      string $v new value
	 * @return     T09PedidoDetalle The current object (for fluent API support)
	 */
	public function setCnProducto($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cn_producto !== $v) {
			$this->cn_producto = $v;
			$this->modifiedColumns[] = T09PedidoDetallePeer::CN_PRODUCTO;
		}

		return $this;
	} // setCnProducto()

	/**
	 * Set the value of [mo_viejo] column.
	 * 
	 * @param      string $v new value
	 * @return     T09PedidoDetalle The current object (for fluent API support)
	 */
	public function setMoViejo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mo_viejo !== $v) {
			$this->mo_viejo = $v;
			$this->modifiedColumns[] = T09PedidoDetallePeer::MO_VIEJO;
		}

		return $this;
	} // setMoViejo()

	/**
	 * Set the value of [mo_nuevo] column.
	 * 
	 * @param      string $v new value
	 * @return     T09PedidoDetalle The current object (for fluent API support)
	 */
	public function setMoNuevo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mo_nuevo !== $v) {
			$this->mo_nuevo = $v;
			$this->modifiedColumns[] = T09PedidoDetallePeer::MO_NUEVO;
		}

		return $this;
	} // setMoNuevo()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_pedido_detalle = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->co_pedido = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->co_producto = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->cn_producto = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->mo_viejo = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->mo_nuevo = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = T09PedidoDetallePeer::NUM_COLUMNS - T09PedidoDetallePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating T09PedidoDetalle object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aT08Pedido !== null && $this->co_pedido !== $this->aT08Pedido->getCoPedido()) {
			$this->aT08Pedido = null;
		}
		if ($this->aT07Producto !== null && $this->co_producto !== $this->aT07Producto->getCoProducto()) {
			$this->aT07Producto = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T09PedidoDetallePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = T09PedidoDetallePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aT08Pedido = null;
			$this->aT07Producto = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseT09PedidoDetalle:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T09PedidoDetallePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			T09PedidoDetallePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseT09PedidoDetalle:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseT09PedidoDetalle:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T09PedidoDetallePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseT09PedidoDetalle:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			T09PedidoDetallePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aT08Pedido !== null) {
				if ($this->aT08Pedido->isModified() || $this->aT08Pedido->isNew()) {
					$affectedRows += $this->aT08Pedido->save($con);
				}
				$this->setT08Pedido($this->aT08Pedido);
			}

			if ($this->aT07Producto !== null) {
				if ($this->aT07Producto->isModified() || $this->aT07Producto->isNew()) {
					$affectedRows += $this->aT07Producto->save($con);
				}
				$this->setT07Producto($this->aT07Producto);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = T09PedidoDetallePeer::CO_PEDIDO_DETALLE;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = T09PedidoDetallePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoPedidoDetalle($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += T09PedidoDetallePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aT08Pedido !== null) {
				if (!$this->aT08Pedido->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aT08Pedido->getValidationFailures());
				}
			}

			if ($this->aT07Producto !== null) {
				if (!$this->aT07Producto->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aT07Producto->getValidationFailures());
				}
			}


			if (($retval = T09PedidoDetallePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = T09PedidoDetallePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoPedidoDetalle();
				break;
			case 1:
				return $this->getCoPedido();
				break;
			case 2:
				return $this->getCoProducto();
				break;
			case 3:
				return $this->getCnProducto();
				break;
			case 4:
				return $this->getMoViejo();
				break;
			case 5:
				return $this->getMoNuevo();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = T09PedidoDetallePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoPedidoDetalle(),
			$keys[1] => $this->getCoPedido(),
			$keys[2] => $this->getCoProducto(),
			$keys[3] => $this->getCnProducto(),
			$keys[4] => $this->getMoViejo(),
			$keys[5] => $this->getMoNuevo(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = T09PedidoDetallePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoPedidoDetalle($value);
				break;
			case 1:
				$this->setCoPedido($value);
				break;
			case 2:
				$this->setCoProducto($value);
				break;
			case 3:
				$this->setCnProducto($value);
				break;
			case 4:
				$this->setMoViejo($value);
				break;
			case 5:
				$this->setMoNuevo($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = T09PedidoDetallePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoPedidoDetalle($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCoPedido($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCoProducto($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCnProducto($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setMoViejo($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setMoNuevo($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(T09PedidoDetallePeer::DATABASE_NAME);

		if ($this->isColumnModified(T09PedidoDetallePeer::CO_PEDIDO_DETALLE)) $criteria->add(T09PedidoDetallePeer::CO_PEDIDO_DETALLE, $this->co_pedido_detalle);
		if ($this->isColumnModified(T09PedidoDetallePeer::CO_PEDIDO)) $criteria->add(T09PedidoDetallePeer::CO_PEDIDO, $this->co_pedido);
		if ($this->isColumnModified(T09PedidoDetallePeer::CO_PRODUCTO)) $criteria->add(T09PedidoDetallePeer::CO_PRODUCTO, $this->co_producto);
		if ($this->isColumnModified(T09PedidoDetallePeer::CN_PRODUCTO)) $criteria->add(T09PedidoDetallePeer::CN_PRODUCTO, $this->cn_producto);
		if ($this->isColumnModified(T09PedidoDetallePeer::MO_VIEJO)) $criteria->add(T09PedidoDetallePeer::MO_VIEJO, $this->mo_viejo);
		if ($this->isColumnModified(T09PedidoDetallePeer::MO_NUEVO)) $criteria->add(T09PedidoDetallePeer::MO_NUEVO, $this->mo_nuevo);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(T09PedidoDetallePeer::DATABASE_NAME);

		$criteria->add(T09PedidoDetallePeer::CO_PEDIDO_DETALLE, $this->co_pedido_detalle);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoPedidoDetalle();
	}

	/**
	 * Generic method to set the primary key (co_pedido_detalle column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoPedidoDetalle($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of T09PedidoDetalle (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCoPedido($this->co_pedido);

		$copyObj->setCoProducto($this->co_producto);

		$copyObj->setCnProducto($this->cn_producto);

		$copyObj->setMoViejo($this->mo_viejo);

		$copyObj->setMoNuevo($this->mo_nuevo);


		$copyObj->setNew(true);

		$copyObj->setCoPedidoDetalle(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     T09PedidoDetalle Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     T09PedidoDetallePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new T09PedidoDetallePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a T08Pedido object.
	 *
	 * @param      T08Pedido $v
	 * @return     T09PedidoDetalle The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setT08Pedido(T08Pedido $v = null)
	{
		if ($v === null) {
			$this->setCoPedido(NULL);
		} else {
			$this->setCoPedido($v->getCoPedido());
		}

		$this->aT08Pedido = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the T08Pedido object, it will not be re-added.
		if ($v !== null) {
			$v->addT09PedidoDetalle($this);
		}

		return $this;
	}


	/**
	 * Get the associated T08Pedido object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     T08Pedido The associated T08Pedido object.
	 * @throws     PropelException
	 */
	public function getT08Pedido(PropelPDO $con = null)
	{
		if ($this->aT08Pedido === null && ($this->co_pedido !== null)) {
			$c = new Criteria(T08PedidoPeer::DATABASE_NAME);
			$c->add(T08PedidoPeer::CO_PEDIDO, $this->co_pedido);
			$this->aT08Pedido = T08PedidoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aT08Pedido->addT09PedidoDetalles($this);
			 */
		}
		return $this->aT08Pedido;
	}

	/**
	 * Declares an association between this object and a T07Producto object.
	 *
	 * @param      T07Producto $v
	 * @return     T09PedidoDetalle The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setT07Producto(T07Producto $v = null)
	{
		if ($v === null) {
			$this->setCoProducto(NULL);
		} else {
			$this->setCoProducto($v->getCoProducto());
		}

		$this->aT07Producto = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the T07Producto object, it will not be re-added.
		if ($v !== null) {
			$v->addT09PedidoDetalle($this);
		}

		return $this;
	}


	/**
	 * Get the associated T07Producto object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     T07Producto The associated T07Producto object.
	 * @throws     PropelException
	 */
	public function getT07Producto(PropelPDO $con = null)
	{
		if ($this->aT07Producto === null && ($this->co_producto !== null)) {
			$c = new Criteria(T07ProductoPeer::DATABASE_NAME);
			$c->add(T07ProductoPeer::CO_PRODUCTO, $this->co_producto);
			$this->aT07Producto = T07ProductoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aT07Producto->addT09PedidoDetalles($this);
			 */
		}
		return $this->aT07Producto;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aT08Pedido = null;
			$this->aT07Producto = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseT09PedidoDetalle:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseT09PedidoDetalle::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseT09PedidoDetalle
