<?php

/**
 * Base class that represents a row from the 't12_factura' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug 20 18:05:54 2013
 *
 * @package    lib.model.om
 */
abstract class BaseT12Factura extends BaseObject  implements Persistent {


  const PEER = 'T12FacturaPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        T12FacturaPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_factura field.
	 * @var        string
	 */
	protected $co_factura;

	/**
	 * The value for the co_cliente field.
	 * @var        int
	 */
	protected $co_cliente;

	/**
	 * The value for the fe_factura field.
	 * @var        string
	 */
	protected $fe_factura;

	/**
	 * The value for the nu_iva field.
	 * @var        string
	 */
	protected $nu_iva;

	/**
	 * The value for the mo_neto field.
	 * @var        string
	 */
	protected $mo_neto;

	/**
	 * The value for the mo_iva field.
	 * @var        string
	 */
	protected $mo_iva;

	/**
	 * The value for the mo_total field.
	 * @var        string
	 */
	protected $mo_total;

	/**
	 * The value for the co_usuario field.
	 * @var        int
	 */
	protected $co_usuario;

	/**
	 * The value for the co_tipo_factura field.
	 * @var        int
	 */
	protected $co_tipo_factura;

	/**
	 * The value for the fecha_creacion field.
	 * @var        string
	 */
	protected $fecha_creacion;

	/**
	 * @var        T10Cliente
	 */
	protected $aT10Cliente;

	/**
	 * @var        T11TipoFactura
	 */
	protected $aT11TipoFactura;

	/**
	 * @var        array T13FacturaDetalle[] Collection to store aggregation of T13FacturaDetalle objects.
	 */
	protected $collT13FacturaDetalles;

	/**
	 * @var        Criteria The criteria used to select the current contents of collT13FacturaDetalles.
	 */
	private $lastT13FacturaDetalleCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseT12Factura object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_factura] column value.
	 * 
	 * @return     string
	 */
	public function getCoFactura()
	{
		return $this->co_factura;
	}

	/**
	 * Get the [co_cliente] column value.
	 * 
	 * @return     int
	 */
	public function getCoCliente()
	{
		return $this->co_cliente;
	}

	/**
	 * Get the [optionally formatted] temporal [fe_factura] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFeFactura($format = 'Y-m-d')
	{
		if ($this->fe_factura === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fe_factura);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fe_factura, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [nu_iva] column value.
	 * 
	 * @return     string
	 */
	public function getNuIva()
	{
		return $this->nu_iva;
	}

	/**
	 * Get the [mo_neto] column value.
	 * 
	 * @return     string
	 */
	public function getMoNeto()
	{
		return $this->mo_neto;
	}

	/**
	 * Get the [mo_iva] column value.
	 * 
	 * @return     string
	 */
	public function getMoIva()
	{
		return $this->mo_iva;
	}

	/**
	 * Get the [mo_total] column value.
	 * 
	 * @return     string
	 */
	public function getMoTotal()
	{
		return $this->mo_total;
	}

	/**
	 * Get the [co_usuario] column value.
	 * 
	 * @return     int
	 */
	public function getCoUsuario()
	{
		return $this->co_usuario;
	}

	/**
	 * Get the [co_tipo_factura] column value.
	 * 
	 * @return     int
	 */
	public function getCoTipoFactura()
	{
		return $this->co_tipo_factura;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_creacion] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaCreacion($format = 'Y-m-d H:i:s')
	{
		if ($this->fecha_creacion === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->fecha_creacion);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_creacion, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [co_factura] column.
	 * 
	 * @param      string $v new value
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setCoFactura($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_factura !== $v) {
			$this->co_factura = $v;
			$this->modifiedColumns[] = T12FacturaPeer::CO_FACTURA;
		}

		return $this;
	} // setCoFactura()

	/**
	 * Set the value of [co_cliente] column.
	 * 
	 * @param      int $v new value
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setCoCliente($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->co_cliente !== $v) {
			$this->co_cliente = $v;
			$this->modifiedColumns[] = T12FacturaPeer::CO_CLIENTE;
		}

		if ($this->aT10Cliente !== null && $this->aT10Cliente->getCoCliente() !== $v) {
			$this->aT10Cliente = null;
		}

		return $this;
	} // setCoCliente()

	/**
	 * Sets the value of [fe_factura] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setFeFactura($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fe_factura !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fe_factura !== null && $tmpDt = new DateTime($this->fe_factura)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fe_factura = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = T12FacturaPeer::FE_FACTURA;
			}
		} // if either are not null

		return $this;
	} // setFeFactura()

	/**
	 * Set the value of [nu_iva] column.
	 * 
	 * @param      string $v new value
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setNuIva($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nu_iva !== $v) {
			$this->nu_iva = $v;
			$this->modifiedColumns[] = T12FacturaPeer::NU_IVA;
		}

		return $this;
	} // setNuIva()

	/**
	 * Set the value of [mo_neto] column.
	 * 
	 * @param      string $v new value
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setMoNeto($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mo_neto !== $v) {
			$this->mo_neto = $v;
			$this->modifiedColumns[] = T12FacturaPeer::MO_NETO;
		}

		return $this;
	} // setMoNeto()

	/**
	 * Set the value of [mo_iva] column.
	 * 
	 * @param      string $v new value
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setMoIva($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mo_iva !== $v) {
			$this->mo_iva = $v;
			$this->modifiedColumns[] = T12FacturaPeer::MO_IVA;
		}

		return $this;
	} // setMoIva()

	/**
	 * Set the value of [mo_total] column.
	 * 
	 * @param      string $v new value
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setMoTotal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mo_total !== $v) {
			$this->mo_total = $v;
			$this->modifiedColumns[] = T12FacturaPeer::MO_TOTAL;
		}

		return $this;
	} // setMoTotal()

	/**
	 * Set the value of [co_usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setCoUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->co_usuario !== $v) {
			$this->co_usuario = $v;
			$this->modifiedColumns[] = T12FacturaPeer::CO_USUARIO;
		}

		return $this;
	} // setCoUsuario()

	/**
	 * Set the value of [co_tipo_factura] column.
	 * 
	 * @param      int $v new value
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setCoTipoFactura($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->co_tipo_factura !== $v) {
			$this->co_tipo_factura = $v;
			$this->modifiedColumns[] = T12FacturaPeer::CO_TIPO_FACTURA;
		}

		if ($this->aT11TipoFactura !== null && $this->aT11TipoFactura->getCoTipoFactura() !== $v) {
			$this->aT11TipoFactura = null;
		}

		return $this;
	} // setCoTipoFactura()

	/**
	 * Sets the value of [fecha_creacion] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     T12Factura The current object (for fluent API support)
	 */
	public function setFechaCreacion($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_creacion !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_creacion !== null && $tmpDt = new DateTime($this->fecha_creacion)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->fecha_creacion = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = T12FacturaPeer::FECHA_CREACION;
			}
		} // if either are not null

		return $this;
	} // setFechaCreacion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_factura = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->co_cliente = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->fe_factura = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->nu_iva = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->mo_neto = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->mo_iva = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->mo_total = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->co_usuario = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->co_tipo_factura = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->fecha_creacion = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = T12FacturaPeer::NUM_COLUMNS - T12FacturaPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating T12Factura object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aT10Cliente !== null && $this->co_cliente !== $this->aT10Cliente->getCoCliente()) {
			$this->aT10Cliente = null;
		}
		if ($this->aT11TipoFactura !== null && $this->co_tipo_factura !== $this->aT11TipoFactura->getCoTipoFactura()) {
			$this->aT11TipoFactura = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T12FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = T12FacturaPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aT10Cliente = null;
			$this->aT11TipoFactura = null;
			$this->collT13FacturaDetalles = null;
			$this->lastT13FacturaDetalleCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseT12Factura:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T12FacturaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			T12FacturaPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseT12Factura:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseT12Factura:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T12FacturaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseT12Factura:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			T12FacturaPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aT10Cliente !== null) {
				if ($this->aT10Cliente->isModified() || $this->aT10Cliente->isNew()) {
					$affectedRows += $this->aT10Cliente->save($con);
				}
				$this->setT10Cliente($this->aT10Cliente);
			}

			if ($this->aT11TipoFactura !== null) {
				if ($this->aT11TipoFactura->isModified() || $this->aT11TipoFactura->isNew()) {
					$affectedRows += $this->aT11TipoFactura->save($con);
				}
				$this->setT11TipoFactura($this->aT11TipoFactura);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = T12FacturaPeer::CO_FACTURA;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = T12FacturaPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoFactura($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += T12FacturaPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collT13FacturaDetalles !== null) {
				foreach ($this->collT13FacturaDetalles as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aT10Cliente !== null) {
				if (!$this->aT10Cliente->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aT10Cliente->getValidationFailures());
				}
			}

			if ($this->aT11TipoFactura !== null) {
				if (!$this->aT11TipoFactura->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aT11TipoFactura->getValidationFailures());
				}
			}


			if (($retval = T12FacturaPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collT13FacturaDetalles !== null) {
					foreach ($this->collT13FacturaDetalles as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = T12FacturaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoFactura();
				break;
			case 1:
				return $this->getCoCliente();
				break;
			case 2:
				return $this->getFeFactura();
				break;
			case 3:
				return $this->getNuIva();
				break;
			case 4:
				return $this->getMoNeto();
				break;
			case 5:
				return $this->getMoIva();
				break;
			case 6:
				return $this->getMoTotal();
				break;
			case 7:
				return $this->getCoUsuario();
				break;
			case 8:
				return $this->getCoTipoFactura();
				break;
			case 9:
				return $this->getFechaCreacion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = T12FacturaPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoFactura(),
			$keys[1] => $this->getCoCliente(),
			$keys[2] => $this->getFeFactura(),
			$keys[3] => $this->getNuIva(),
			$keys[4] => $this->getMoNeto(),
			$keys[5] => $this->getMoIva(),
			$keys[6] => $this->getMoTotal(),
			$keys[7] => $this->getCoUsuario(),
			$keys[8] => $this->getCoTipoFactura(),
			$keys[9] => $this->getFechaCreacion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = T12FacturaPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoFactura($value);
				break;
			case 1:
				$this->setCoCliente($value);
				break;
			case 2:
				$this->setFeFactura($value);
				break;
			case 3:
				$this->setNuIva($value);
				break;
			case 4:
				$this->setMoNeto($value);
				break;
			case 5:
				$this->setMoIva($value);
				break;
			case 6:
				$this->setMoTotal($value);
				break;
			case 7:
				$this->setCoUsuario($value);
				break;
			case 8:
				$this->setCoTipoFactura($value);
				break;
			case 9:
				$this->setFechaCreacion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = T12FacturaPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoFactura($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCoCliente($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFeFactura($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNuIva($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setMoNeto($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setMoIva($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setMoTotal($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCoUsuario($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCoTipoFactura($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFechaCreacion($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(T12FacturaPeer::DATABASE_NAME);

		if ($this->isColumnModified(T12FacturaPeer::CO_FACTURA)) $criteria->add(T12FacturaPeer::CO_FACTURA, $this->co_factura);
		if ($this->isColumnModified(T12FacturaPeer::CO_CLIENTE)) $criteria->add(T12FacturaPeer::CO_CLIENTE, $this->co_cliente);
		if ($this->isColumnModified(T12FacturaPeer::FE_FACTURA)) $criteria->add(T12FacturaPeer::FE_FACTURA, $this->fe_factura);
		if ($this->isColumnModified(T12FacturaPeer::NU_IVA)) $criteria->add(T12FacturaPeer::NU_IVA, $this->nu_iva);
		if ($this->isColumnModified(T12FacturaPeer::MO_NETO)) $criteria->add(T12FacturaPeer::MO_NETO, $this->mo_neto);
		if ($this->isColumnModified(T12FacturaPeer::MO_IVA)) $criteria->add(T12FacturaPeer::MO_IVA, $this->mo_iva);
		if ($this->isColumnModified(T12FacturaPeer::MO_TOTAL)) $criteria->add(T12FacturaPeer::MO_TOTAL, $this->mo_total);
		if ($this->isColumnModified(T12FacturaPeer::CO_USUARIO)) $criteria->add(T12FacturaPeer::CO_USUARIO, $this->co_usuario);
		if ($this->isColumnModified(T12FacturaPeer::CO_TIPO_FACTURA)) $criteria->add(T12FacturaPeer::CO_TIPO_FACTURA, $this->co_tipo_factura);
		if ($this->isColumnModified(T12FacturaPeer::FECHA_CREACION)) $criteria->add(T12FacturaPeer::FECHA_CREACION, $this->fecha_creacion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(T12FacturaPeer::DATABASE_NAME);

		$criteria->add(T12FacturaPeer::CO_FACTURA, $this->co_factura);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoFactura();
	}

	/**
	 * Generic method to set the primary key (co_factura column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoFactura($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of T12Factura (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCoCliente($this->co_cliente);

		$copyObj->setFeFactura($this->fe_factura);

		$copyObj->setNuIva($this->nu_iva);

		$copyObj->setMoNeto($this->mo_neto);

		$copyObj->setMoIva($this->mo_iva);

		$copyObj->setMoTotal($this->mo_total);

		$copyObj->setCoUsuario($this->co_usuario);

		$copyObj->setCoTipoFactura($this->co_tipo_factura);

		$copyObj->setFechaCreacion($this->fecha_creacion);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getT13FacturaDetalles() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addT13FacturaDetalle($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setCoFactura(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     T12Factura Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     T12FacturaPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new T12FacturaPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a T10Cliente object.
	 *
	 * @param      T10Cliente $v
	 * @return     T12Factura The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setT10Cliente(T10Cliente $v = null)
	{
		if ($v === null) {
			$this->setCoCliente(NULL);
		} else {
			$this->setCoCliente($v->getCoCliente());
		}

		$this->aT10Cliente = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the T10Cliente object, it will not be re-added.
		if ($v !== null) {
			$v->addT12Factura($this);
		}

		return $this;
	}


	/**
	 * Get the associated T10Cliente object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     T10Cliente The associated T10Cliente object.
	 * @throws     PropelException
	 */
	public function getT10Cliente(PropelPDO $con = null)
	{
		if ($this->aT10Cliente === null && ($this->co_cliente !== null)) {
			$c = new Criteria(T10ClientePeer::DATABASE_NAME);
			$c->add(T10ClientePeer::CO_CLIENTE, $this->co_cliente);
			$this->aT10Cliente = T10ClientePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aT10Cliente->addT12Facturas($this);
			 */
		}
		return $this->aT10Cliente;
	}

	/**
	 * Declares an association between this object and a T11TipoFactura object.
	 *
	 * @param      T11TipoFactura $v
	 * @return     T12Factura The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setT11TipoFactura(T11TipoFactura $v = null)
	{
		if ($v === null) {
			$this->setCoTipoFactura(NULL);
		} else {
			$this->setCoTipoFactura($v->getCoTipoFactura());
		}

		$this->aT11TipoFactura = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the T11TipoFactura object, it will not be re-added.
		if ($v !== null) {
			$v->addT12Factura($this);
		}

		return $this;
	}


	/**
	 * Get the associated T11TipoFactura object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     T11TipoFactura The associated T11TipoFactura object.
	 * @throws     PropelException
	 */
	public function getT11TipoFactura(PropelPDO $con = null)
	{
		if ($this->aT11TipoFactura === null && ($this->co_tipo_factura !== null)) {
			$c = new Criteria(T11TipoFacturaPeer::DATABASE_NAME);
			$c->add(T11TipoFacturaPeer::CO_TIPO_FACTURA, $this->co_tipo_factura);
			$this->aT11TipoFactura = T11TipoFacturaPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aT11TipoFactura->addT12Facturas($this);
			 */
		}
		return $this->aT11TipoFactura;
	}

	/**
	 * Clears out the collT13FacturaDetalles collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addT13FacturaDetalles()
	 */
	public function clearT13FacturaDetalles()
	{
		$this->collT13FacturaDetalles = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collT13FacturaDetalles collection (array).
	 *
	 * By default this just sets the collT13FacturaDetalles collection to an empty array (like clearcollT13FacturaDetalles());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initT13FacturaDetalles()
	{
		$this->collT13FacturaDetalles = array();
	}

	/**
	 * Gets an array of T13FacturaDetalle objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this T12Factura has previously been saved, it will retrieve
	 * related T13FacturaDetalles from storage. If this T12Factura is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array T13FacturaDetalle[]
	 * @throws     PropelException
	 */
	public function getT13FacturaDetalles($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(T12FacturaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collT13FacturaDetalles === null) {
			if ($this->isNew()) {
			   $this->collT13FacturaDetalles = array();
			} else {

				$criteria->add(T13FacturaDetallePeer::CO_FACTURA, $this->co_factura);

				T13FacturaDetallePeer::addSelectColumns($criteria);
				$this->collT13FacturaDetalles = T13FacturaDetallePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(T13FacturaDetallePeer::CO_FACTURA, $this->co_factura);

				T13FacturaDetallePeer::addSelectColumns($criteria);
				if (!isset($this->lastT13FacturaDetalleCriteria) || !$this->lastT13FacturaDetalleCriteria->equals($criteria)) {
					$this->collT13FacturaDetalles = T13FacturaDetallePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastT13FacturaDetalleCriteria = $criteria;
		return $this->collT13FacturaDetalles;
	}

	/**
	 * Returns the number of related T13FacturaDetalle objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related T13FacturaDetalle objects.
	 * @throws     PropelException
	 */
	public function countT13FacturaDetalles(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(T12FacturaPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collT13FacturaDetalles === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(T13FacturaDetallePeer::CO_FACTURA, $this->co_factura);

				$count = T13FacturaDetallePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(T13FacturaDetallePeer::CO_FACTURA, $this->co_factura);

				if (!isset($this->lastT13FacturaDetalleCriteria) || !$this->lastT13FacturaDetalleCriteria->equals($criteria)) {
					$count = T13FacturaDetallePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collT13FacturaDetalles);
				}
			} else {
				$count = count($this->collT13FacturaDetalles);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a T13FacturaDetalle object to this object
	 * through the T13FacturaDetalle foreign key attribute.
	 *
	 * @param      T13FacturaDetalle $l T13FacturaDetalle
	 * @return     void
	 * @throws     PropelException
	 */
	public function addT13FacturaDetalle(T13FacturaDetalle $l)
	{
		if ($this->collT13FacturaDetalles === null) {
			$this->initT13FacturaDetalles();
		}
		if (!in_array($l, $this->collT13FacturaDetalles, true)) { // only add it if the **same** object is not already associated
			array_push($this->collT13FacturaDetalles, $l);
			$l->setT12Factura($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this T12Factura is new, it will return
	 * an empty collection; or if this T12Factura has previously
	 * been saved, it will retrieve related T13FacturaDetalles from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in T12Factura.
	 */
	public function getT13FacturaDetallesJoinT07Producto($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(T12FacturaPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collT13FacturaDetalles === null) {
			if ($this->isNew()) {
				$this->collT13FacturaDetalles = array();
			} else {

				$criteria->add(T13FacturaDetallePeer::CO_FACTURA, $this->co_factura);

				$this->collT13FacturaDetalles = T13FacturaDetallePeer::doSelectJoinT07Producto($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(T13FacturaDetallePeer::CO_FACTURA, $this->co_factura);

			if (!isset($this->lastT13FacturaDetalleCriteria) || !$this->lastT13FacturaDetalleCriteria->equals($criteria)) {
				$this->collT13FacturaDetalles = T13FacturaDetallePeer::doSelectJoinT07Producto($criteria, $con, $join_behavior);
			}
		}
		$this->lastT13FacturaDetalleCriteria = $criteria;

		return $this->collT13FacturaDetalles;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collT13FacturaDetalles) {
				foreach ((array) $this->collT13FacturaDetalles as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collT13FacturaDetalles = null;
			$this->aT10Cliente = null;
			$this->aT11TipoFactura = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseT12Factura:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseT12Factura::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseT12Factura
