<?php

/**
 * Base class that represents a row from the 't01_usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug 20 18:05:54 2013
 *
 * @package    lib.model.om
 */
abstract class BaseT01Usuario extends BaseObject  implements Persistent {


  const PEER = 'T01UsuarioPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        T01UsuarioPeer
	 */
	protected static $peer;

	/**
	 * The value for the co_usuario field.
	 * @var        int
	 */
	protected $co_usuario;

	/**
	 * The value for the nb_usuario field.
	 * @var        string
	 */
	protected $nb_usuario;

	/**
	 * The value for the ap_usuario field.
	 * @var        string
	 */
	protected $ap_usuario;

	/**
	 * The value for the nu_cedula field.
	 * @var        string
	 */
	protected $nu_cedula;

	/**
	 * The value for the tx_login field.
	 * @var        string
	 */
	protected $tx_login;

	/**
	 * The value for the tx_password field.
	 * @var        string
	 */
	protected $tx_password;

	/**
	 * The value for the co_rol field.
	 * @var        int
	 */
	protected $co_rol;

	/**
	 * The value for the in_activo field.
	 * @var        boolean
	 */
	protected $in_activo;

	/**
	 * @var        T02Rol
	 */
	protected $aT02Rol;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseT01Usuario object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_usuario] column value.
	 * 
	 * @return     int
	 */
	public function getCoUsuario()
	{
		return $this->co_usuario;
	}

	/**
	 * Get the [nb_usuario] column value.
	 * 
	 * @return     string
	 */
	public function getNbUsuario()
	{
		return $this->nb_usuario;
	}

	/**
	 * Get the [ap_usuario] column value.
	 * 
	 * @return     string
	 */
	public function getApUsuario()
	{
		return $this->ap_usuario;
	}

	/**
	 * Get the [nu_cedula] column value.
	 * 
	 * @return     string
	 */
	public function getNuCedula()
	{
		return $this->nu_cedula;
	}

	/**
	 * Get the [tx_login] column value.
	 * 
	 * @return     string
	 */
	public function getTxLogin()
	{
		return $this->tx_login;
	}

	/**
	 * Get the [tx_password] column value.
	 * 
	 * @return     string
	 */
	public function getTxPassword()
	{
		return $this->tx_password;
	}

	/**
	 * Get the [co_rol] column value.
	 * 
	 * @return     int
	 */
	public function getCoRol()
	{
		return $this->co_rol;
	}

	/**
	 * Get the [in_activo] column value.
	 * 
	 * @return     boolean
	 */
	public function getInActivo()
	{
		return $this->in_activo;
	}

	/**
	 * Set the value of [co_usuario] column.
	 * 
	 * @param      int $v new value
	 * @return     T01Usuario The current object (for fluent API support)
	 */
	public function setCoUsuario($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->co_usuario !== $v) {
			$this->co_usuario = $v;
			$this->modifiedColumns[] = T01UsuarioPeer::CO_USUARIO;
		}

		return $this;
	} // setCoUsuario()

	/**
	 * Set the value of [nb_usuario] column.
	 * 
	 * @param      string $v new value
	 * @return     T01Usuario The current object (for fluent API support)
	 */
	public function setNbUsuario($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nb_usuario !== $v) {
			$this->nb_usuario = $v;
			$this->modifiedColumns[] = T01UsuarioPeer::NB_USUARIO;
		}

		return $this;
	} // setNbUsuario()

	/**
	 * Set the value of [ap_usuario] column.
	 * 
	 * @param      string $v new value
	 * @return     T01Usuario The current object (for fluent API support)
	 */
	public function setApUsuario($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ap_usuario !== $v) {
			$this->ap_usuario = $v;
			$this->modifiedColumns[] = T01UsuarioPeer::AP_USUARIO;
		}

		return $this;
	} // setApUsuario()

	/**
	 * Set the value of [nu_cedula] column.
	 * 
	 * @param      string $v new value
	 * @return     T01Usuario The current object (for fluent API support)
	 */
	public function setNuCedula($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nu_cedula !== $v) {
			$this->nu_cedula = $v;
			$this->modifiedColumns[] = T01UsuarioPeer::NU_CEDULA;
		}

		return $this;
	} // setNuCedula()

	/**
	 * Set the value of [tx_login] column.
	 * 
	 * @param      string $v new value
	 * @return     T01Usuario The current object (for fluent API support)
	 */
	public function setTxLogin($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_login !== $v) {
			$this->tx_login = $v;
			$this->modifiedColumns[] = T01UsuarioPeer::TX_LOGIN;
		}

		return $this;
	} // setTxLogin()

	/**
	 * Set the value of [tx_password] column.
	 * 
	 * @param      string $v new value
	 * @return     T01Usuario The current object (for fluent API support)
	 */
	public function setTxPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_password !== $v) {
			$this->tx_password = $v;
			$this->modifiedColumns[] = T01UsuarioPeer::TX_PASSWORD;
		}

		return $this;
	} // setTxPassword()

	/**
	 * Set the value of [co_rol] column.
	 * 
	 * @param      int $v new value
	 * @return     T01Usuario The current object (for fluent API support)
	 */
	public function setCoRol($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->co_rol !== $v) {
			$this->co_rol = $v;
			$this->modifiedColumns[] = T01UsuarioPeer::CO_ROL;
		}

		if ($this->aT02Rol !== null && $this->aT02Rol->getCoRol() !== $v) {
			$this->aT02Rol = null;
		}

		return $this;
	} // setCoRol()

	/**
	 * Set the value of [in_activo] column.
	 * 
	 * @param      boolean $v new value
	 * @return     T01Usuario The current object (for fluent API support)
	 */
	public function setInActivo($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->in_activo !== $v) {
			$this->in_activo = $v;
			$this->modifiedColumns[] = T01UsuarioPeer::IN_ACTIVO;
		}

		return $this;
	} // setInActivo()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_usuario = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->nb_usuario = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->ap_usuario = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->nu_cedula = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->tx_login = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->tx_password = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->co_rol = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->in_activo = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 8; // 8 = T01UsuarioPeer::NUM_COLUMNS - T01UsuarioPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating T01Usuario object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aT02Rol !== null && $this->co_rol !== $this->aT02Rol->getCoRol()) {
			$this->aT02Rol = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T01UsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = T01UsuarioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aT02Rol = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseT01Usuario:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T01UsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			T01UsuarioPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseT01Usuario:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseT01Usuario:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T01UsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseT01Usuario:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			T01UsuarioPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aT02Rol !== null) {
				if ($this->aT02Rol->isModified() || $this->aT02Rol->isNew()) {
					$affectedRows += $this->aT02Rol->save($con);
				}
				$this->setT02Rol($this->aT02Rol);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = T01UsuarioPeer::CO_USUARIO;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = T01UsuarioPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoUsuario($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += T01UsuarioPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aT02Rol !== null) {
				if (!$this->aT02Rol->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aT02Rol->getValidationFailures());
				}
			}


			if (($retval = T01UsuarioPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = T01UsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoUsuario();
				break;
			case 1:
				return $this->getNbUsuario();
				break;
			case 2:
				return $this->getApUsuario();
				break;
			case 3:
				return $this->getNuCedula();
				break;
			case 4:
				return $this->getTxLogin();
				break;
			case 5:
				return $this->getTxPassword();
				break;
			case 6:
				return $this->getCoRol();
				break;
			case 7:
				return $this->getInActivo();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = T01UsuarioPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoUsuario(),
			$keys[1] => $this->getNbUsuario(),
			$keys[2] => $this->getApUsuario(),
			$keys[3] => $this->getNuCedula(),
			$keys[4] => $this->getTxLogin(),
			$keys[5] => $this->getTxPassword(),
			$keys[6] => $this->getCoRol(),
			$keys[7] => $this->getInActivo(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = T01UsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoUsuario($value);
				break;
			case 1:
				$this->setNbUsuario($value);
				break;
			case 2:
				$this->setApUsuario($value);
				break;
			case 3:
				$this->setNuCedula($value);
				break;
			case 4:
				$this->setTxLogin($value);
				break;
			case 5:
				$this->setTxPassword($value);
				break;
			case 6:
				$this->setCoRol($value);
				break;
			case 7:
				$this->setInActivo($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = T01UsuarioPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoUsuario($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setNbUsuario($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setApUsuario($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setNuCedula($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTxLogin($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTxPassword($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCoRol($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setInActivo($arr[$keys[7]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(T01UsuarioPeer::DATABASE_NAME);

		if ($this->isColumnModified(T01UsuarioPeer::CO_USUARIO)) $criteria->add(T01UsuarioPeer::CO_USUARIO, $this->co_usuario);
		if ($this->isColumnModified(T01UsuarioPeer::NB_USUARIO)) $criteria->add(T01UsuarioPeer::NB_USUARIO, $this->nb_usuario);
		if ($this->isColumnModified(T01UsuarioPeer::AP_USUARIO)) $criteria->add(T01UsuarioPeer::AP_USUARIO, $this->ap_usuario);
		if ($this->isColumnModified(T01UsuarioPeer::NU_CEDULA)) $criteria->add(T01UsuarioPeer::NU_CEDULA, $this->nu_cedula);
		if ($this->isColumnModified(T01UsuarioPeer::TX_LOGIN)) $criteria->add(T01UsuarioPeer::TX_LOGIN, $this->tx_login);
		if ($this->isColumnModified(T01UsuarioPeer::TX_PASSWORD)) $criteria->add(T01UsuarioPeer::TX_PASSWORD, $this->tx_password);
		if ($this->isColumnModified(T01UsuarioPeer::CO_ROL)) $criteria->add(T01UsuarioPeer::CO_ROL, $this->co_rol);
		if ($this->isColumnModified(T01UsuarioPeer::IN_ACTIVO)) $criteria->add(T01UsuarioPeer::IN_ACTIVO, $this->in_activo);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(T01UsuarioPeer::DATABASE_NAME);

		$criteria->add(T01UsuarioPeer::CO_USUARIO, $this->co_usuario);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getCoUsuario();
	}

	/**
	 * Generic method to set the primary key (co_usuario column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoUsuario($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of T01Usuario (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setNbUsuario($this->nb_usuario);

		$copyObj->setApUsuario($this->ap_usuario);

		$copyObj->setNuCedula($this->nu_cedula);

		$copyObj->setTxLogin($this->tx_login);

		$copyObj->setTxPassword($this->tx_password);

		$copyObj->setCoRol($this->co_rol);

		$copyObj->setInActivo($this->in_activo);


		$copyObj->setNew(true);

		$copyObj->setCoUsuario(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     T01Usuario Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     T01UsuarioPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new T01UsuarioPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a T02Rol object.
	 *
	 * @param      T02Rol $v
	 * @return     T01Usuario The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setT02Rol(T02Rol $v = null)
	{
		if ($v === null) {
			$this->setCoRol(NULL);
		} else {
			$this->setCoRol($v->getCoRol());
		}

		$this->aT02Rol = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the T02Rol object, it will not be re-added.
		if ($v !== null) {
			$v->addT01Usuario($this);
		}

		return $this;
	}


	/**
	 * Get the associated T02Rol object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     T02Rol The associated T02Rol object.
	 * @throws     PropelException
	 */
	public function getT02Rol(PropelPDO $con = null)
	{
		if ($this->aT02Rol === null && ($this->co_rol !== null)) {
			$c = new Criteria(T02RolPeer::DATABASE_NAME);
			$c->add(T02RolPeer::CO_ROL, $this->co_rol);
			$this->aT02Rol = T02RolPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aT02Rol->addT01Usuarios($this);
			 */
		}
		return $this->aT02Rol;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aT02Rol = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseT01Usuario:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseT01Usuario::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseT01Usuario
