<?php

/**
 * Base class that represents a row from the 't10_cliente' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Aug 20 18:05:54 2013
 *
 * @package    lib.model.om
 */
abstract class BaseT10Cliente extends BaseObject  implements Persistent {


  const PEER = 'T10ClientePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        T10ClientePeer
	 */
	protected static $peer;

	/**
	 * The value for the co_cliente field.
	 * @var        string
	 */
	protected $co_cliente;

	/**
	 * The value for the co_documento field.
	 * @var        int
	 */
	protected $co_documento;

	/**
	 * The value for the tx_dni field.
	 * @var        string
	 */
	protected $tx_dni;

	/**
	 * The value for the tx_nombre field.
	 * @var        string
	 */
	protected $tx_nombre;

	/**
	 * The value for the tx_direccion field.
	 * @var        string
	 */
	protected $tx_direccion;

	/**
	 * The value for the tx_telefono field.
	 * @var        string
	 */
	protected $tx_telefono;

	/**
	 * The value for the nu_limite_credito field.
	 * @var        string
	 */
	protected $nu_limite_credito;

	/**
	 * @var        T05Documento
	 */
	protected $aT05Documento;

	/**
	 * @var        array T12Factura[] Collection to store aggregation of T12Factura objects.
	 */
	protected $collT12Facturas;

	/**
	 * @var        Criteria The criteria used to select the current contents of collT12Facturas.
	 */
	private $lastT12FacturaCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseT10Cliente object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [co_cliente] column value.
	 * 
	 * @return     string
	 */
	public function getCoCliente()
	{
		return $this->co_cliente;
	}

	/**
	 * Get the [co_documento] column value.
	 * 
	 * @return     int
	 */
	public function getCoDocumento()
	{
		return $this->co_documento;
	}

	/**
	 * Get the [tx_dni] column value.
	 * 
	 * @return     string
	 */
	public function getTxDni()
	{
		return $this->tx_dni;
	}

	/**
	 * Get the [tx_nombre] column value.
	 * 
	 * @return     string
	 */
	public function getTxNombre()
	{
		return $this->tx_nombre;
	}

	/**
	 * Get the [tx_direccion] column value.
	 * 
	 * @return     string
	 */
	public function getTxDireccion()
	{
		return $this->tx_direccion;
	}

	/**
	 * Get the [tx_telefono] column value.
	 * 
	 * @return     string
	 */
	public function getTxTelefono()
	{
		return $this->tx_telefono;
	}

	/**
	 * Get the [nu_limite_credito] column value.
	 * 
	 * @return     string
	 */
	public function getNuLimiteCredito()
	{
		return $this->nu_limite_credito;
	}

	/**
	 * Set the value of [co_cliente] column.
	 * 
	 * @param      string $v new value
	 * @return     T10Cliente The current object (for fluent API support)
	 */
	public function setCoCliente($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->co_cliente !== $v) {
			$this->co_cliente = $v;
			$this->modifiedColumns[] = T10ClientePeer::CO_CLIENTE;
		}

		return $this;
	} // setCoCliente()

	/**
	 * Set the value of [co_documento] column.
	 * 
	 * @param      int $v new value
	 * @return     T10Cliente The current object (for fluent API support)
	 */
	public function setCoDocumento($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->co_documento !== $v) {
			$this->co_documento = $v;
			$this->modifiedColumns[] = T10ClientePeer::CO_DOCUMENTO;
		}

		if ($this->aT05Documento !== null && $this->aT05Documento->getCoDocumento() !== $v) {
			$this->aT05Documento = null;
		}

		return $this;
	} // setCoDocumento()

	/**
	 * Set the value of [tx_dni] column.
	 * 
	 * @param      string $v new value
	 * @return     T10Cliente The current object (for fluent API support)
	 */
	public function setTxDni($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_dni !== $v) {
			$this->tx_dni = $v;
			$this->modifiedColumns[] = T10ClientePeer::TX_DNI;
		}

		return $this;
	} // setTxDni()

	/**
	 * Set the value of [tx_nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     T10Cliente The current object (for fluent API support)
	 */
	public function setTxNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_nombre !== $v) {
			$this->tx_nombre = $v;
			$this->modifiedColumns[] = T10ClientePeer::TX_NOMBRE;
		}

		return $this;
	} // setTxNombre()

	/**
	 * Set the value of [tx_direccion] column.
	 * 
	 * @param      string $v new value
	 * @return     T10Cliente The current object (for fluent API support)
	 */
	public function setTxDireccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_direccion !== $v) {
			$this->tx_direccion = $v;
			$this->modifiedColumns[] = T10ClientePeer::TX_DIRECCION;
		}

		return $this;
	} // setTxDireccion()

	/**
	 * Set the value of [tx_telefono] column.
	 * 
	 * @param      string $v new value
	 * @return     T10Cliente The current object (for fluent API support)
	 */
	public function setTxTelefono($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tx_telefono !== $v) {
			$this->tx_telefono = $v;
			$this->modifiedColumns[] = T10ClientePeer::TX_TELEFONO;
		}

		return $this;
	} // setTxTelefono()

	/**
	 * Set the value of [nu_limite_credito] column.
	 * 
	 * @param      string $v new value
	 * @return     T10Cliente The current object (for fluent API support)
	 */
	public function setNuLimiteCredito($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nu_limite_credito !== $v) {
			$this->nu_limite_credito = $v;
			$this->modifiedColumns[] = T10ClientePeer::NU_LIMITE_CREDITO;
		}

		return $this;
	} // setNuLimiteCredito()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->co_cliente = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->co_documento = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->tx_dni = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->tx_nombre = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->tx_direccion = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->tx_telefono = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->nu_limite_credito = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = T10ClientePeer::NUM_COLUMNS - T10ClientePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating T10Cliente object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aT05Documento !== null && $this->co_documento !== $this->aT05Documento->getCoDocumento()) {
			$this->aT05Documento = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T10ClientePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = T10ClientePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aT05Documento = null;
			$this->collT12Facturas = null;
			$this->lastT12FacturaCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseT10Cliente:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T10ClientePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			T10ClientePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseT10Cliente:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseT10Cliente:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(T10ClientePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseT10Cliente:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			T10ClientePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aT05Documento !== null) {
				if ($this->aT05Documento->isModified() || $this->aT05Documento->isNew()) {
					$affectedRows += $this->aT05Documento->save($con);
				}
				$this->setT05Documento($this->aT05Documento);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = T10ClientePeer::CO_CLIENTE;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = T10ClientePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setCoCliente($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += T10ClientePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collT12Facturas !== null) {
				foreach ($this->collT12Facturas as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aT05Documento !== null) {
				if (!$this->aT05Documento->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aT05Documento->getValidationFailures());
				}
			}


			if (($retval = T10ClientePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collT12Facturas !== null) {
					foreach ($this->collT12Facturas as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = T10ClientePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getCoCliente();
				break;
			case 1:
				return $this->getCoDocumento();
				break;
			case 2:
				return $this->getTxDni();
				break;
			case 3:
				return $this->getTxNombre();
				break;
			case 4:
				return $this->getTxDireccion();
				break;
			case 5:
				return $this->getTxTelefono();
				break;
			case 6:
				return $this->getNuLimiteCredito();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = T10ClientePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getCoCliente(),
			$keys[1] => $this->getCoDocumento(),
			$keys[2] => $this->getTxDni(),
			$keys[3] => $this->getTxNombre(),
			$keys[4] => $this->getTxDireccion(),
			$keys[5] => $this->getTxTelefono(),
			$keys[6] => $this->getNuLimiteCredito(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = T10ClientePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setCoCliente($value);
				break;
			case 1:
				$this->setCoDocumento($value);
				break;
			case 2:
				$this->setTxDni($value);
				break;
			case 3:
				$this->setTxNombre($value);
				break;
			case 4:
				$this->setTxDireccion($value);
				break;
			case 5:
				$this->setTxTelefono($value);
				break;
			case 6:
				$this->setNuLimiteCredito($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = T10ClientePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setCoCliente($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCoDocumento($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setTxDni($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTxNombre($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTxDireccion($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTxTelefono($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setNuLimiteCredito($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(T10ClientePeer::DATABASE_NAME);

		if ($this->isColumnModified(T10ClientePeer::CO_CLIENTE)) $criteria->add(T10ClientePeer::CO_CLIENTE, $this->co_cliente);
		if ($this->isColumnModified(T10ClientePeer::CO_DOCUMENTO)) $criteria->add(T10ClientePeer::CO_DOCUMENTO, $this->co_documento);
		if ($this->isColumnModified(T10ClientePeer::TX_DNI)) $criteria->add(T10ClientePeer::TX_DNI, $this->tx_dni);
		if ($this->isColumnModified(T10ClientePeer::TX_NOMBRE)) $criteria->add(T10ClientePeer::TX_NOMBRE, $this->tx_nombre);
		if ($this->isColumnModified(T10ClientePeer::TX_DIRECCION)) $criteria->add(T10ClientePeer::TX_DIRECCION, $this->tx_direccion);
		if ($this->isColumnModified(T10ClientePeer::TX_TELEFONO)) $criteria->add(T10ClientePeer::TX_TELEFONO, $this->tx_telefono);
		if ($this->isColumnModified(T10ClientePeer::NU_LIMITE_CREDITO)) $criteria->add(T10ClientePeer::NU_LIMITE_CREDITO, $this->nu_limite_credito);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(T10ClientePeer::DATABASE_NAME);

		$criteria->add(T10ClientePeer::CO_CLIENTE, $this->co_cliente);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     string
	 */
	public function getPrimaryKey()
	{
		return $this->getCoCliente();
	}

	/**
	 * Generic method to set the primary key (co_cliente column).
	 *
	 * @param      string $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setCoCliente($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of T10Cliente (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCoDocumento($this->co_documento);

		$copyObj->setTxDni($this->tx_dni);

		$copyObj->setTxNombre($this->tx_nombre);

		$copyObj->setTxDireccion($this->tx_direccion);

		$copyObj->setTxTelefono($this->tx_telefono);

		$copyObj->setNuLimiteCredito($this->nu_limite_credito);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getT12Facturas() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addT12Factura($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setCoCliente(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     T10Cliente Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     T10ClientePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new T10ClientePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a T05Documento object.
	 *
	 * @param      T05Documento $v
	 * @return     T10Cliente The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setT05Documento(T05Documento $v = null)
	{
		if ($v === null) {
			$this->setCoDocumento(NULL);
		} else {
			$this->setCoDocumento($v->getCoDocumento());
		}

		$this->aT05Documento = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the T05Documento object, it will not be re-added.
		if ($v !== null) {
			$v->addT10Cliente($this);
		}

		return $this;
	}


	/**
	 * Get the associated T05Documento object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     T05Documento The associated T05Documento object.
	 * @throws     PropelException
	 */
	public function getT05Documento(PropelPDO $con = null)
	{
		if ($this->aT05Documento === null && ($this->co_documento !== null)) {
			$c = new Criteria(T05DocumentoPeer::DATABASE_NAME);
			$c->add(T05DocumentoPeer::CO_DOCUMENTO, $this->co_documento);
			$this->aT05Documento = T05DocumentoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aT05Documento->addT10Clientes($this);
			 */
		}
		return $this->aT05Documento;
	}

	/**
	 * Clears out the collT12Facturas collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addT12Facturas()
	 */
	public function clearT12Facturas()
	{
		$this->collT12Facturas = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collT12Facturas collection (array).
	 *
	 * By default this just sets the collT12Facturas collection to an empty array (like clearcollT12Facturas());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initT12Facturas()
	{
		$this->collT12Facturas = array();
	}

	/**
	 * Gets an array of T12Factura objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this T10Cliente has previously been saved, it will retrieve
	 * related T12Facturas from storage. If this T10Cliente is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array T12Factura[]
	 * @throws     PropelException
	 */
	public function getT12Facturas($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(T10ClientePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collT12Facturas === null) {
			if ($this->isNew()) {
			   $this->collT12Facturas = array();
			} else {

				$criteria->add(T12FacturaPeer::CO_CLIENTE, $this->co_cliente);

				T12FacturaPeer::addSelectColumns($criteria);
				$this->collT12Facturas = T12FacturaPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(T12FacturaPeer::CO_CLIENTE, $this->co_cliente);

				T12FacturaPeer::addSelectColumns($criteria);
				if (!isset($this->lastT12FacturaCriteria) || !$this->lastT12FacturaCriteria->equals($criteria)) {
					$this->collT12Facturas = T12FacturaPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastT12FacturaCriteria = $criteria;
		return $this->collT12Facturas;
	}

	/**
	 * Returns the number of related T12Factura objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related T12Factura objects.
	 * @throws     PropelException
	 */
	public function countT12Facturas(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(T10ClientePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collT12Facturas === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(T12FacturaPeer::CO_CLIENTE, $this->co_cliente);

				$count = T12FacturaPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(T12FacturaPeer::CO_CLIENTE, $this->co_cliente);

				if (!isset($this->lastT12FacturaCriteria) || !$this->lastT12FacturaCriteria->equals($criteria)) {
					$count = T12FacturaPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collT12Facturas);
				}
			} else {
				$count = count($this->collT12Facturas);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a T12Factura object to this object
	 * through the T12Factura foreign key attribute.
	 *
	 * @param      T12Factura $l T12Factura
	 * @return     void
	 * @throws     PropelException
	 */
	public function addT12Factura(T12Factura $l)
	{
		if ($this->collT12Facturas === null) {
			$this->initT12Facturas();
		}
		if (!in_array($l, $this->collT12Facturas, true)) { // only add it if the **same** object is not already associated
			array_push($this->collT12Facturas, $l);
			$l->setT10Cliente($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this T10Cliente is new, it will return
	 * an empty collection; or if this T10Cliente has previously
	 * been saved, it will retrieve related T12Facturas from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in T10Cliente.
	 */
	public function getT12FacturasJoinT11TipoFactura($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(T10ClientePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collT12Facturas === null) {
			if ($this->isNew()) {
				$this->collT12Facturas = array();
			} else {

				$criteria->add(T12FacturaPeer::CO_CLIENTE, $this->co_cliente);

				$this->collT12Facturas = T12FacturaPeer::doSelectJoinT11TipoFactura($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(T12FacturaPeer::CO_CLIENTE, $this->co_cliente);

			if (!isset($this->lastT12FacturaCriteria) || !$this->lastT12FacturaCriteria->equals($criteria)) {
				$this->collT12Facturas = T12FacturaPeer::doSelectJoinT11TipoFactura($criteria, $con, $join_behavior);
			}
		}
		$this->lastT12FacturaCriteria = $criteria;

		return $this->collT12Facturas;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collT12Facturas) {
				foreach ((array) $this->collT12Facturas as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collT12Facturas = null;
			$this->aT05Documento = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseT10Cliente:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseT10Cliente::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseT10Cliente
