dev:
  propel:
    param:
      classname: DebugPDO
test:
  propel:
    param:
      classname: DebugPDO
all:
  propel:
    class: sfPropelDatabase
    param:
      classname: PropelPDO
      dsn: 'pgsql:host=localhost;dbname=venta'
      username: postgres
      password: '1234'
      encoding: utf8
      persistent: true
      pooling: true
