<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/10/15 22:40:14
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'imagen' => 
  array (
    'is_secure' => false,
  ),
);
