<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2014/07/30 18:31:28
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoCliente/actions/actions.class.php');

