<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/07/30 18:31:12
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'imagen' => 
  array (
    'is_secure' => false,
  ),
);
