<?php
// auto-generated by sfGeneratorConfigHandler
// date: 2014/10/15 22:40:14
require sfConfig::get('sf_symfony_lib_dir').'/plugins/sfCompat10Plugin/config/config.php';
require_once(sfConfig::get('sf_module_cache_dir').'/autoPedido/actions/actions.class.php');

